feat(LH-72231): SEC Resource
CiscoDevNet/terraform-provider-cdo pull request #102
Opened 2023-11-08 18:02 UTC by weilueluo

https://jira-eng-rtp3.cisco.com/jira/browse/LH-72231

### Description
- Read SEC
- Update SEC (empty implementation)
- Delete SEC
- Create SEC

2023-11-13 09:36 UTC, siddhuwarrier requested changes

2023-11-13 09:36 UTC, siddhuwarrier commented on provider/internal/connector/sec/operation.go
> +	// e.g. updateOutp, err := resource.client.UpdateExample(ctx, ...)
Please delete this comment

2023-11-13 09:36 UTC, siddhuwarrier commented on provider/internal/connector/sec/resource.go
> +		MarkdownDescription: "TODO",
??????

2023-11-13 09:36 UTC, siddhuwarrier commented on provider/internal/connector/sec/resource.go
> +				MarkdownDescription: "TODO",
??????????????????

2023-11-13 09:36 UTC, siddhuwarrier commented on provider/internal/connector/sec/resource.go
> +				MarkdownDescription: "TODO",
???????

2023-11-13 09:46 UTC, weilueluo commented on client/connector/sec/create.go
> +	// 3. get sec bootstrap data
done! 👍

2023-11-13 09:46 UTC, weilueluo commented on provider/internal/cdfmc/resource_test.go
> +	t.Skip("we cant delete a fmc so this test cannot be run, or we should find a way to spin up new environment, neither seems uneasy, skipping for now.")
done! 👍

2023-11-13 09:47 UTC, weilueluo commented on provider/internal/connector/sec/operation.go
> +	// e.g. updateOutp, err := resource.client.UpdateExample(ctx, ...)
done! 👍

2023-11-13 09:47 UTC, weilueluo commented on provider/internal/connector/sec/operation.go
> +	// stateData.ID = types.StringValue(updateOutp.Uid)
done! 👍

2023-11-13 09:59 UTC, weilueluo commented on provider/internal/connector/sec/resource.go
> +				MarkdownDescription: "TODO",
done 👍

2023-11-13 09:59 UTC, weilueluo commented on provider/internal/connector/sec/resource.go
> +				MarkdownDescription: "TODO",
done 👍

2023-11-13 09:59 UTC, weilueluo commented on provider/internal/connector/sec/resource.go
> +				MarkdownDescription: "TODO",
done 👍

2023-11-13 10:04 UTC, hazital commented on client/connector/sec/create_test.go
> +func TestSECCreate(t *testing.T) {
pls add tests for the delete, read, and update as well

2023-11-14 09:19 UTC, weilueluo commented
superseded by https://github.com/CiscoDevNet/terraform-provider-cdo/pull/104

2023-11-14 09:19 UTC, closed without merging