Read cdFMC
CiscoDevNet/terraform-provider-cdo pull request #20
Opened 2023-08-22 13:59 UTC by weilueluo

https://jira-eng-rtp3.cisco.com/jira/browse/LH-67704 (or Github issue ID)

### Description

2023-08-23 08:36 UTC, hazital approved these changes
LGTM, could pls add tests and rename the files so it will follow the Go naming convention?

2023-08-23 09:17 UTC, siddhuwarrier requested changes

2023-08-23 09:17 UTC, siddhuwarrier commented on client/device/readbynameandtype.go
> +package device
Same comment as Tal's above around file name

2023-08-23 09:17 UTC, siddhuwarrier commented on client/device/readbyuid.go
> +package device
Same comment as Tal's above around file name

2023-08-23 11:32 UTC, weilueluo commented on client/device/readallbytype.go
Yes agree, I will make the change since it is getting too long and hurt readability.

But also note that Golang's convention does not have an opinion on underscore with filename, but filename with underscore have special meaning in Golang. For example, `go test` only look for filename ended with `_test`, and `go build` will exclude filename ended with different architecture, e.g. `name_amd64.go`.

2023-08-23 11:34 UTC, weilueluo commented on client/device/readbynameandtype.go
> +package device
Done 🙂

2023-08-24 09:55 UTC, siddhuwarrier approved these changes

2023-08-24 10:47 UTC, merged